feat: ignore camelcase rule for __webpack variables
nextcloud/eslint-config pull request #530
Opened 2023-05-20 15:27 UTC by kesselb

```
// eslint-disable-next-line camelcase
__webpack_nonce__ = 'foobar'
// eslint-disable-next-line camelcase
__webpack_public_path__ = 'foobar'
```

Motivation: `__webpack_nonce__` will always violate the camelcase rule. 

The error is usually ignored with `// eslint-disable-next-line camelcase`. 
It sounds reasonable to me to add the ignore rule by default. 

An alternative approach could be to define `__webpack_nonce__` as globals. The advantage is that also the un-def violation is gone and globals are by default excluded from the camelcase rule. But it's weird to define `__webpack_nonce` as global for every app using eslint when the variable is only available when bundled with webpack.

2023-05-25 11:04 UTC, skjnldsv commented on index.js
> +			ignoreGlobals: true
```suggestion
			ignoreGlobals: true,
```

2023-05-25 11:04 UTC, skjnldsv requested changes
See comment

2023-05-25 12:21 UTC, kesselb commented on index.js
> +			ignoreGlobals: true
Done

2023-05-26 11:36 UTC, susnux approved these changes

2023-05-26 11:39 UTC, merged